# Generated by Django 4.2.1 on 2023-06-06 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingClubDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_description', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettingDefaultDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_donation', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettingDefaultWeekBaseDonation',
            fields=[
                ('distance', models.IntegerField(primary_key=True, serialize=False)),
                ('base_donation', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingRegisteredMileage',
            fields=[
                ('distance', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingStravaClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_url', models.CharField(max_length=1024)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voz_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettingWeekBaseDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('base_donation', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'week_num'], name='weeklyTrack_year_7c2c02_idx'), models.Index(fields=['distance', 'year', 'week_num'], name='weeklyTrack_distanc_5f8039_idx')],
                'unique_together': {('distance', 'year', 'week_num')},
            },
        ),
        migrations.CreateModel(
            name='SettingDefaultDonationByWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('default_donation', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'week_num'], name='weeklyTrack_year_2c7cf0_idx')],
                'unique_together': {('year', 'week_num')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('distance', models.FloatField(default=0.0)),
                ('runs', models.IntegerField(default=0)),
                ('longest_run', models.FloatField(default=0.0)),
                ('average_pace', models.FloatField(default=0.0)),
                ('elevation_gain', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('registered_mileage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklyTracking.settingregisteredmileage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'week_num'], name='weeklyTrack_year_6b532f_idx'), models.Index(fields=['user', 'year', 'week_num'], name='weeklyTrack_user_id_6f28ab_idx')],
                'unique_together': {('user', 'year', 'week_num')},
            },
        ),
    ]
