# Generated by Django 4.2.1 on 2023-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogress',
            name='actual_donation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='donation',
            field=models.IntegerField(default=0),
        ),
    ]
