# Generated by Django 4.1 on 2023-05-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyprogress',
            unique_together={('runner', 'year', 'week_num')},
        ),
    ]
