# Generated by Django 4.2.1 on 2023-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0002_weeklyprogress_actual_donation_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weeklyprogress',
            index=models.Index(fields=['year', 'week_num', 'distance'], name='weeklyTrack_year_32ca23_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogress',
            index=models.Index(fields=['year', 'week_num', 'donation'], name='weeklyTrack_year_c3f7fc_idx'),
        ),
    ]
