# Generated by Django 4.2.1 on 2023-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0003_settingclubdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingregisteredmileage',
            name='donation_per_km',
        ),
        migrations.CreateModel(
            name='WeekBaseDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('base_donation', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('distance', 'year', 'week_num')},
            },
        ),
    ]
