# Generated by Django 4.2.1 on 2023-06-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0003_weeklyprogress_weeklytrack_year_32ca23_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='strava_club_joined',
            field=models.BooleanField(default=False),
        ),
    ]
