# Generated by Django 4.2.1 on 2023-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0004_userprofile_strava_club_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'week_num'], name='weeklyTrack_year_895248_idx')],
                'unique_together': {('year', 'week_num')},
            },
        ),
    ]
