# Generated by Django 4.2.1 on 2023-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0005_defaultweekbasedonation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultWeekBaseDonation',
            new_name='SettingDefaultWeekBaseDonation',
        ),
        migrations.RenameModel(
            old_name='WeekBaseDonation',
            new_name='SettingWeekBaseDonation',
        ),
        migrations.CreateModel(
            name='SettingDefaultDonationByWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('default_donation', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('year', 'week_num')},
            },
        ),
    ]
