# Generated by Django 4.2.1 on 2023-06-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0005_weeklypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypost',
            name='post',
            field=models.TextField(default=''),
        ),
    ]
