# Generated by Django 4.2.1 on 2023-06-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0006_weeklypost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypost',
            name='post',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ActualDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'week_num'], name='weeklyTrack_year_101cb8_idx')],
                'unique_together': {('year', 'week_num')},
            },
        ),
    ]
