# Generated by Django 4.2.1 on 2023-06-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0006_rename_defaultweekbasedonation_settingdefaultweekbasedonation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravarunner',
            name='strava_refresh_token',
            field=models.CharField(default='', max_length=64),
        ),
    ]
