# Generated by Django 4.2.1 on 2023-06-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0008_alter_stravarunner_strava_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingStravaAPIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=512)),
                ('client_secret', models.CharField(max_length=512)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
