# Generated by Django 4.2.1 on 2023-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0009_settingstravaapiclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravarunner',
            name='voz_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
