# Generated by Django 4.2.1 on 2023-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0012_alter_stravarunner_strava_refresh_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='settingdefaultdonationbyweek',
            index=models.Index(fields=['year', 'week_num'], name='weeklyTrack_year_2c7cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='settingweekbasedonation',
            index=models.Index(fields=['year', 'week_num'], name='weeklyTrack_year_7c2c02_idx'),
        ),
        migrations.AddIndex(
            model_name='settingweekbasedonation',
            index=models.Index(fields=['distance', 'year', 'week_num'], name='weeklyTrack_distanc_5f8039_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogress',
            index=models.Index(fields=['year', 'week_num'], name='weeklyTrack_year_6b532f_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogress',
            index=models.Index(fields=['runner', 'year', 'week_num'], name='weeklyTrack_runner__2fd0d5_idx'),
        ),
    ]
