# Generated by Django 4.2.1 on 2023-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyTracking', '0013_settingdefaultdonationbyweek_weeklytrack_year_2c7cf0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogress',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
